# -*- coding: utf-8 -*-
"""Fraud_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uSwRUm4LWGqiN_S7EJ-MdXOf9m80Jw5t

Fraud Detection Sandbox - Synthetic Data
"""

import numpy as np
import pandas as pd
from datetime import datetime, timedelta
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.animation as animation
import joblib
import os

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, IsolationForest
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    classification_report,
    average_precision_score,
    roc_curve,
    auc,
    precision_recall_curve
)

from imblearn.over_sampling import SMOTE

np.random.seed(42)

MODEL_PATH = "fraud_model.pkl"

# DATA GENERATION
def generate_base_data(num_records=50000):
    user_ids = [f"USER_{i:04d}" for i in np.random.randint(1000, 2000, size=num_records)]

    categories = ['groceries', 'entertainment', 'utilities', 'online_shopping', 'travel']
    chosen_categories = np.random.choice(categories, size=num_records, p=[0.4, 0.2, 0.1, 0.2, 0.1])

    start_date = datetime(2026, 5, 1)
    timestamps = [start_date + timedelta(
        days=int(np.random.randint(0, 30)),
        hours=int(np.random.randint(0, 24)),
        minutes=int(np.random.randint(0, 60))
    ) for _ in range(num_records)]

    amounts = np.random.lognormal(mean=3.5, sigma=0.8, size=num_records)

    return pd.DataFrame({
        'user_id': user_ids,
        'timestamp': timestamps,
        'amount': np.round(amounts, 2),
        'category': chosen_categories,
        'is_fraud': 0
    })

# adding fraud patterns
def inject_fraud_patterns(df):
    df = df.copy()

    p1 = df.sample(frac=0.005).index
    df.loc[p1, 'timestamp'] = df.loc[p1, 'timestamp'].apply(
        lambda dt: dt.replace(hour=np.random.choice([2, 3, 4]))
    )
    df.loc[p1, 'amount'] = np.random.uniform(2000, 5000, len(p1))
    df.loc[p1, 'is_fraud'] = 1

    p2 = df[df['is_fraud'] == 0].sample(frac=0.005).index
    df.loc[p2, 'amount'] = np.random.uniform(1, 5, len(p2))
    df.loc[p2, 'category'] = 'online_shopping'
    df.loc[p2, 'is_fraud'] = 1

    print("\nClass Distribution:\n", df['is_fraud'].value_counts(normalize=True))
    return df

# feature engineering
def engineer_features(df):
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df = df.sort_values(by=['user_id', 'timestamp']).reset_index(drop=True)

    df['hour'] = df['timestamp'].dt.hour
    df['is_night'] = df['hour'].isin([2, 3, 4]).astype(int)
    df['time_diff'] = df.groupby('user_id')['timestamp'].diff().dt.total_seconds().fillna(86400)

    rolling = df.groupby('user_id').apply(
        lambda x: x.set_index('timestamp')['amount'].rolling('1h').count()
    )
    rolling = rolling.reset_index(name='rolling_tx_count_1h')

    df = pd.merge(df, rolling, on=['user_id', 'timestamp'], how='left')

    df = pd.get_dummies(df, columns=['category'], drop_first=True)

    return df

# training the model and storing it
def train_and_save_model():
    df = generate_base_data(60000)
    df = inject_fraud_patterns(df)
    df = engineer_features(df)

    X = df.drop(columns=['user_id', 'timestamp', 'is_fraud'])
    y = df['is_fraud']

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, stratify=y, test_size=0.3, random_state=42
    )

    sm = SMOTE(random_state=42)
    X_train_res, y_train_res = sm.fit_resample(X_train, y_train)

    model = RandomForestClassifier(n_estimators=100, random_state=42)
    model.fit(X_train_res, y_train_res)

    joblib.dump((model, X.columns), MODEL_PATH)

    evaluate_model(model, X_test, y_test)

    return model, X.columns

# loading the model
def load_model():
    if os.path.exists(MODEL_PATH):
        return joblib.load(MODEL_PATH)
    else:
        return train_and_save_model()

# evaluation of model
def evaluate_model(model, X_test, y_test):
    preds = model.predict(X_test)
    probs = model.predict_proba(X_test)[:, 1]

    print(classification_report(y_test, preds))

    # ROC Curve
    fpr, tpr, _ = roc_curve(y_test, probs)
    plt.figure()
    plt.plot(fpr, tpr, label="ROC Curve")
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")
    plt.title("ROC Curve")
    plt.legend()
    plt.savefig("roc_curve.png")
    plt.close()
    # Precision-Recall Curve
    precision, recall, _ = precision_recall_curve(y_test, probs)
    plt.figure()
    plt.plot(recall, precision, label="PR Curve")
    plt.xlabel("Recall")
    plt.ylabel("Precision")
    plt.title("Precision-Recall Curve")
    plt.legend()
    plt.savefig("pr_curve.png")
    plt.close()

def plot_dashboard(df, model, X):
    sns.set_theme(style="whitegrid")
    fig, axes = plt.subplots(1, 3, figsize=(22, 6))

    # Step 1: Fraud Count Plot
    sns.countplot(x=df['is_fraud'], ax=axes[0])
    axes[0].set_title("Fraud vs Normal Transactions")
    axes[0].set_xlabel("Transaction Type (0 = Normal, 1 = Fraud)")
    axes[0].set_ylabel("Count")

    # Step 2: Scatter Plot
    sample = df.sample(5000)
    sns.scatterplot(
        data=sample,
        x='hour',
        y='amount',
        hue='is_fraud',
        palette={0: 'blue', 1: 'red'},
        ax=axes[1]
    )
    axes[1].set_title("Transaction Amount vs Hour")
    axes[1].set_xlabel("Hour of Day")
    axes[1].set_ylabel("Transaction Amount")
    axes[1].legend(title="Fraud (0=No, 1=Yes)")

    # Step 3: Feature Importance
    importances = pd.Series(model.feature_importances_, index=X.columns)
    importances = importances.sort_values().tail(10)

    importances.plot(kind='barh', ax=axes[2])
    axes[2].set_title("Top 10 Important Features")
    axes[2].set_xlabel("Importance Score")
    axes[2].set_ylabel("Features")

    plt.tight_layout()
    plt.savefig("fraud_dashboard.png")
    plt.close()

def create_animation(df):
    fig, ax = plt.subplots(figsize=(10, 6))
    sample_df = df.sample(3000).sort_values('hour')

    def create_animation(df):
      fig, ax = plt.subplots(figsize=(10, 6))
      sample_df = df.sort_values('hour')

    def update(hour):
        ax.clear()
        current = sample_df[sample_df['hour'] <= hour]
        normal = current[current['is_fraud'] == 0]
        ax.scatter(
            normal['hour'],
            normal['amount'],
            color='blue',
            alpha=0.4,
            s=30
        )

        # Step 3: fraud points
        fraud = current[current['is_fraud'] == 1]

        # glow layer
        ax.scatter(
            fraud['hour'],
            fraud['amount'],
            color='red',
            s=200,
            alpha=0.15
        )

        # main point
        ax.scatter(
            fraud['hour'],
            fraud['amount'],
            color='red',
            s=60,
            edgecolors='black',
            linewidth=0.5
        )

        # Step 4: labels
        ax.set_xlim(-1, 24)
        ax.set_ylim(0, 5500)

        ax.set_title(f"Fraud Detection Scan (Hour ≤ {hour})")
        ax.set_xlabel("Hour of Day")
        ax.set_ylabel("Transaction Amount")

    ani = animation.FuncAnimation(fig, update, frames=range(24))
    ani.save("fraud_animation.gif", writer='pillow')
    plt.close()

# Main pipeline
def run_pipeline():
    df = generate_base_data(60000)
    df = inject_fraud_patterns(df)
    df = engineer_features(df)
    # Fixed sample for consistent visualization
    fixed_sample = df.sample(5000, random_state=42)
    model, cols = train_and_save_model()
    # Step: Use same sample everywhere
    plot_dashboard(fixed_sample, model, fixed_sample.drop(columns=['user_id', 'timestamp', 'is_fraud']))
    create_animation(fixed_sample)


if __name__ == "__main__":
    run_pipeline()

